### PR TITLE
Added lagom14 modules

### LINKED ISSUE #14: Lagom 1.4 support
When used with Lagom 1.4, we get the following exception:
`Exception in thread "main" java.lang.NoSuchMethodError: play.api.Environment.mode()Lscala/Enumeration$Value`

This is due to the change to Environment.mode in Play2.6: https://www.playframework.com/documentation/2.6.x/Migration26#Scala-Mode-changes

In order to support Lagom 1.4, it seems no additional changes are needed except from a version that was compiled with Play 2.6. 

We are prepared to create a pull request. Do you want this as additional modules for lagom14?

### PR DESCRIPTION
**Pull request by olivierdeckers**
Fixes #14

### CODE REVIEW

**Comment by huntc** [comment]
Thanks @olivierdeckers - can you please confirm that you've signed the CLA? https://www.lightbend.com/contribute/cla

**Comment by olivierdeckers** [comment]
I have already signed it when contributing to the lagom repository.

**Comment by huntc** [comment]
Thanks @olivierdeckers I shall look at making a release in the next day or so.

**Comment by fsat** [comment]
@olivierdeckers - we have just released version `2.1.0` from the Sonatype's staging repo. Once the Maven sync is complete, this version should be available for you to use.

**Comment by olivierdeckers** [comment]
Thanks!

**Pull request merged**
